# Question 1

In [1]:
numbersdiv =[]
for x in range(2000,3201):
        if x % 7 == 0 and x%5 != 0:
            numbersdiv.append(x)

In [2]:
print(numbersdiv)

[2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142, 2149, 2156, 2163, 2177, 2184, 2191, 2198, 2212, 2219, 2226, 2233, 2247, 2254, 2261, 2268, 2282, 2289, 2296, 2303, 2317, 2324, 2331, 2338, 2352, 2359, 2366, 2373, 2387, 2394, 2401, 2408, 2422, 2429, 2436, 2443, 2457, 2464, 2471, 2478, 2492, 2499, 2506, 2513, 2527, 2534, 2541, 2548, 2562, 2569, 2576, 2583, 2597, 2604, 2611, 2618, 2632, 2639, 2646, 2653, 2667, 2674, 2681, 2688, 2702, 2709, 2716, 2723, 2737, 2744, 2751, 2758, 2772, 2779, 2786, 2793, 2807, 2814, 2821, 2828, 2842, 2849, 2856, 2863, 2877, 2884, 2891, 2898, 2912, 2919, 2926, 2933, 2947, 2954, 2961, 2968, 2982, 2989, 2996, 3003, 3017, 3024, 3031, 3038, 3052, 3059, 3066, 3073, 3087, 3094, 3101, 3108, 3122, 3129, 3136, 3143, 3157, 3164, 3171, 3178, 3192, 3199]


# Question 2

In [3]:
x = input()

8


In [4]:
input_a = int(x) + 1

In [5]:
list1 = 1
for w in range(1,input_a):
     list1 = list1 * w

In [6]:
print(list1)

40320


# Question 3

In [7]:
 x = input()

2


In [8]:
input_a = int(x) + 1

In [9]:
mydict={}
for w in range(1,input_a):
    mydict[w]=w**2

In [10]:
print(mydict)

{1: 1, 2: 4}


# Question 4

In [11]:
def missing_char(word,n):
    w = word[:n]+word[n+1:]
    print(w)

In [12]:
missing_char("Hello",0)

ello


# Question 5

In [13]:
import numpy as np

In [14]:
a = np.array([[1,2],[3,4],[4,5]])

In [15]:
a

array([[1, 2],
       [3, 4],
       [4, 5]])

In [16]:
list1 = a.tolist()

In [17]:
list1

[[1, 2], [3, 4], [4, 5]]

# Question 6

In [18]:
import numpy as np

In [19]:
matrix1 = np.array([0,1,2]) 
matrix1

array([0, 1, 2])

In [20]:
matrix2 = np.array([2,1,0])
matrix2

array([2, 1, 0])

In [21]:
matrixcov = np.cov(matrix1,matrix2)

In [22]:
print(matrixcov)

[[ 1. -1.]
 [-1.  1.]]


# Question 7

In [23]:
import math

In [24]:
numbers = input("Please enter D: ")

Please enter D: 2, 3, 4, 1


In [25]:
numbers = numbers.split(',')

In [26]:
result_list = []

In [27]:
for D in numbers:
    Q = round(math.sqrt(2 * 50 * int(D) / 30))
    result_list.append(Q)  

In [28]:
print(result_list)

[3, 3, 4, 2]
