In [1]:
import numpy as np

In [14]:
matrix1 = np.array([0,1,2]) 
matrix1

array([0, 1, 2])

In [15]:
matrix2 = np.array([2,1,0])
matrix2

array([2, 1, 0])

In [20]:
matrixcov = np.cov(matrix1,matrix2)

In [21]:
print(matrixcov)

[[ 1. -1.]
 [-1.  1.]]
